### PR TITLE
mimetype package to mimetype/browser

### PR DESCRIPTION
**Pull request by dalbodeule**
This error seems to occur because cloudflare worker does not directly support the node module. This error seems to occur because the mimetext module has not yet been changed to browser support code.

So, I changed all the supported code to browser support code. Please PR after checking in your environment.

### CODE REVIEW

**Comment by JacobLinCool** [comment]
Hello @dalbodeule,

Thanks for the contribution! Can you run `pnpm changeset` to add one changeset so that I can give the credit to you in the release notes and changelog!

**Comment by dalbodeule** [comment]
As a result of the test, some parts of tsconfig.json need to be further touched. I will post the results a little later.

**Comment by dalbodeule** [comment]
I completed the commit yesterday and confirmed that the build is proceeding normally. Additionally, some code modifications were completed. Please confirm and merge.

**Review by JacobLinCool — APPROVED** [review]

**Comment by JacobLinCool** [comment]
Thanks for your contribution!

**Pull request merged**
